// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:9000' | (string & {});
};

export type GetOpenapiJsonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.json';
};

export type GetOpenapiJsonResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agents';
};

export type GetAgentsErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetAgentsError = GetAgentsErrors[keyof GetAgentsErrors];

export type GetAgentsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        isDemo: boolean;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetAgentsResponse = GetAgentsResponses[keyof GetAgentsResponses];

export type CreateAgentData = {
    body: {
        name: string;
        isDemo?: boolean;
    };
    path?: never;
    query?: never;
    url: '/api/agents';
};

export type CreateAgentErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type CreateAgentError = CreateAgentErrors[keyof CreateAgentErrors];

export type CreateAgentResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        isDemo: boolean;
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateAgentResponse = CreateAgentResponses[keyof CreateAgentResponses];

export type DeleteAgentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agents/{id}';
};

export type DeleteAgentErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type DeleteAgentError = DeleteAgentErrors[keyof DeleteAgentErrors];

export type DeleteAgentResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
    };
};

export type DeleteAgentResponse = DeleteAgentResponses[keyof DeleteAgentResponses];

export type GetAgentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agents/{id}';
};

export type GetAgentErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetAgentError = GetAgentErrors[keyof GetAgentErrors];

export type GetAgentResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        isDemo: boolean;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetAgentResponse = GetAgentResponses[keyof GetAgentResponses];

export type UpdateAgentData = {
    body?: {
        name?: string;
        isDemo?: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agents/{id}';
};

export type UpdateAgentErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UpdateAgentError = UpdateAgentErrors[keyof UpdateAgentErrors];

export type UpdateAgentResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        isDemo: boolean;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateAgentResponse = UpdateAgentResponses[keyof UpdateAgentResponses];

export type GetChatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chats';
};

export type GetChatsErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetChatsError = GetChatsErrors[keyof GetChatsErrors];

export type GetChatsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        agentId: string;
        sessionId: string;
        title: string | null;
        selectedTools: string | number | boolean | null | {
            [key: string]: unknown;
        } | Array<unknown> | null;
        totalPromptTokens: number;
        totalCompletionTokens: number;
        totalTokens: number;
        lastModel: string | null;
        lastContextWindow: number | null;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetChatsResponse = GetChatsResponses[keyof GetChatsResponses];

export type CreateChatData = {
    body: {
        agentId: string;
    };
    path?: never;
    query?: never;
    url: '/api/chats';
};

export type CreateChatErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type CreateChatError = CreateChatErrors[keyof CreateChatErrors];

export type CreateChatResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        agentId: string;
        sessionId: string;
        title: string | null;
        selectedTools: string | number | boolean | null | {
            [key: string]: unknown;
        } | Array<unknown> | null;
        totalPromptTokens: number;
        totalCompletionTokens: number;
        totalTokens: number;
        lastModel: string | null;
        lastContextWindow: number | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateChatResponse = CreateChatResponses[keyof CreateChatResponses];

export type DeleteChatData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/chats/{id}';
};

export type DeleteChatErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type DeleteChatError = DeleteChatErrors[keyof DeleteChatErrors];

export type DeleteChatResponses = {
    /**
     * Default Response
     */
    204: null;
};

export type DeleteChatResponse = DeleteChatResponses[keyof DeleteChatResponses];

export type GetChatByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/chats/{id}';
};

export type GetChatByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetChatByIdError = GetChatByIdErrors[keyof GetChatByIdErrors];

export type GetChatByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        agentId: string;
        sessionId: string;
        title: string | null;
        selectedTools: string | number | boolean | null | {
            [key: string]: unknown;
        } | Array<unknown> | null;
        totalPromptTokens: number;
        totalCompletionTokens: number;
        totalTokens: number;
        lastModel: string | null;
        lastContextWindow: number | null;
        createdAt: string;
        updatedAt: string;
        messages: Array<{
            id: string;
            chatId: string;
            role: string;
            content: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown>;
            createdAt: string;
        }>;
    };
};

export type GetChatByIdResponse = GetChatByIdResponses[keyof GetChatByIdResponses];

export type UpdateChatData = {
    body?: {
        title?: string | null;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/chats/{id}';
};

export type UpdateChatErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UpdateChatError = UpdateChatErrors[keyof UpdateChatErrors];

export type UpdateChatResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        agentId: string;
        sessionId: string;
        title: string | null;
        selectedTools: string | number | boolean | null | {
            [key: string]: unknown;
        } | Array<unknown> | null;
        totalPromptTokens: number;
        totalCompletionTokens: number;
        totalTokens: number;
        lastModel: string | null;
        lastContextWindow: number | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateChatResponse = UpdateChatResponses[keyof UpdateChatResponses];

export type GetChatToolsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/chats/{id}/tools';
};

export type GetChatToolsErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetChatToolsError = GetChatToolsErrors[keyof GetChatToolsErrors];

export type GetChatToolsResponses = {
    /**
     * Default Response
     */
    200: {
        selectedTools: Array<string> | null;
    };
};

export type GetChatToolsResponse = GetChatToolsResponses[keyof GetChatToolsResponses];

export type UpdateChatToolsData = {
    body: {
        toolIds: Array<string> | null;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/chats/{id}/tools';
};

export type UpdateChatToolsErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UpdateChatToolsError = UpdateChatToolsErrors[keyof UpdateChatToolsErrors];

export type UpdateChatToolsResponses = {
    /**
     * Default Response
     */
    200: {
        selectedTools: Array<string> | null;
    };
};

export type UpdateChatToolsResponse = UpdateChatToolsResponses[keyof UpdateChatToolsResponses];

export type AddChatToolsData = {
    body: {
        toolIds: Array<string>;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/chats/{id}/tools/select';
};

export type AddChatToolsErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type AddChatToolsError = AddChatToolsErrors[keyof AddChatToolsErrors];

export type AddChatToolsResponses = {
    /**
     * Default Response
     */
    200: {
        selectedTools: Array<string>;
    };
};

export type AddChatToolsResponse = AddChatToolsResponses[keyof AddChatToolsResponses];

export type RemoveChatToolsData = {
    body: {
        toolIds: Array<string>;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/chats/{id}/tools/deselect';
};

export type RemoveChatToolsErrors = {
    /**
     * Default Response
     */
    400: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type RemoveChatToolsError = RemoveChatToolsErrors[keyof RemoveChatToolsErrors];

export type RemoveChatToolsResponses = {
    /**
     * Default Response
     */
    200: {
        selectedTools: Array<string>;
    };
};

export type RemoveChatToolsResponse = RemoveChatToolsResponses[keyof RemoveChatToolsResponses];

export type SelectAllChatToolsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/chats/{id}/tools/select-all';
};

export type SelectAllChatToolsErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type SelectAllChatToolsError = SelectAllChatToolsErrors[keyof SelectAllChatToolsErrors];

export type SelectAllChatToolsResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type SelectAllChatToolsResponse = SelectAllChatToolsResponses[keyof SelectAllChatToolsResponses];

export type DeselectAllChatToolsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/chats/{id}/tools/deselect-all';
};

export type DeselectAllChatToolsErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type DeselectAllChatToolsError = DeselectAllChatToolsErrors[keyof DeselectAllChatToolsErrors];

export type DeselectAllChatToolsResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type DeselectAllChatToolsResponse = DeselectAllChatToolsResponses[keyof DeselectAllChatToolsResponses];

export type ResetChatTokensData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/api/chats/{sessionId}/reset-tokens';
};

export type ResetChatTokensErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type ResetChatTokensError = ResetChatTokensErrors[keyof ResetChatTokensErrors];

export type ResetChatTokensResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type ResetChatTokensResponse = ResetChatTokensResponses[keyof ResetChatTokensResponses];

export type GetInteractionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by agent ID
         */
        agentId?: string;
    };
    url: '/api/interactions';
};

export type GetInteractionsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        agentId: string;
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1487
         */
        request: {
            model: string;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1186
             */
            messages: Array<{
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                role: 'developer';
                name?: string;
            } | {
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                role: 'system';
                name?: string;
            } | {
                content: string | Array<{
                    type: 'text';
                    text: string;
                } | {
                    type: 'image_url';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L765
                     */
                    image_url: {
                        url: string;
                        detail: 'auto' | 'low' | 'high';
                    };
                } | {
                    type: 'input_audio';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L792
                     */
                    input_audio: {
                        data: string;
                        format: 'wav' | 'mp3';
                    };
                } | {
                    type: 'file';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L732
                     */
                    file: {
                        file_data?: string;
                        file_id?: string;
                        filename?: string;
                    };
                }>;
                role: 'user';
                name?: string;
            } | {
                role: 'assistant';
                audio?: {
                    id: string;
                } | null;
                content?: string | Array<{
                    type: 'text';
                    text: string;
                }> | Array<{
                    type: 'refusal';
                    refusal: string;
                }> | null;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
                 */
                function_call?: {
                    arguments: string;
                    name: string;
                } | null;
                name?: string;
                refusal?: string | null;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
                 */
                tool_calls?: Array<{
                    id: string;
                    type: 'function';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                     */
                    function: {
                        arguments: string;
                        name: string;
                    };
                } | {
                    id: string;
                    type: 'custom';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                     */
                    custom: {
                        input: string;
                        name: string;
                    };
                }>;
            } | {
                role: 'tool';
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                tool_call_id: string;
            } | {
                role: 'function';
                content: string | null;
                name: string;
            }>;
            /**
             *
             * A function tool that can be used to generate a response.
             *
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1392
             *
             */
            tools?: Array<{
                type: 'function';
                /**
                 * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L174
                 */
                function: {
                    name: string;
                    description?: string;
                    /**
                     *
                     * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
                     *
                     * The parameters the functions accepts, described as a JSON Schema object. See the
                     * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
                     * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
                     * documentation about the format.
                     *
                     * Omitting parameters defines a function with an empty parameter list.
                     *
                     */
                    parameters?: {
                        [key: string]: unknown;
                    };
                    strict?: boolean | null;
                };
            } | {
                type: 'custom';
                custom: {
                    /**
                     * The name of the custom tool, used to identify it in tool calls
                     */
                    name: string;
                    /**
                     * Optional description of the custom tool, used to provide more context
                     */
                    description?: string;
                    /**
                     * The input format for the custom tool. Default is unconstrained text.
                     */
                    format?: {
                        /**
                         * Unconstrained text format. Always `text`
                         */
                        type: 'text';
                    } | {
                        type: 'grammar';
                        /**
                         * Your chosen grammar
                         */
                        grammar: {
                            /**
                             * The grammar definition
                             */
                            definition: string;
                            /**
                             * The syntax of the grammar definition
                             */
                            syntax: 'lark' | 'regex';
                        };
                    };
                };
            }>;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1405
             */
            tool_choice?: 'none' | 'auto' | 'required' | {
                type: 'allowed_tools';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1455
                 */
                allowed_tools: {
                    /**
                     *
                     * Constrains the tools available to the model to a pre-defined set.
                     *
                     * auto allows the model to pick from among the allowed tools and generate a
                     * message.
                     *
                     * required requires the model to call one or more of the allowed tools.
                     *
                     */
                    mode: 'auto' | 'required';
                    /**
                     * A list of tool definitions that the model should be allowed to call
                     */
                    tools: Array<{
                        [key: string]: {
                            type: 'function';
                            /**
                             * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L174
                             */
                            function: {
                                name: string;
                                description?: string;
                                /**
                                 *
                                 * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
                                 *
                                 * The parameters the functions accepts, described as a JSON Schema object. See the
                                 * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
                                 * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
                                 * documentation about the format.
                                 *
                                 * Omitting parameters defines a function with an empty parameter list.
                                 *
                                 */
                                parameters?: {
                                    [key: string]: unknown;
                                };
                                strict?: boolean | null;
                            };
                        };
                    }>;
                };
            } | {
                type: 'function';
                function: {
                    name: string;
                };
            } | {
                type: 'custom';
                custom: {
                    /**
                     * The name of the custom tool, used to identify it in tool calls
                     */
                    name: string;
                    /**
                     * Optional description of the custom tool, used to provide more context
                     */
                    description?: string;
                    /**
                     * The input format for the custom tool. Default is unconstrained text.
                     */
                    format?: {
                        /**
                         * Unconstrained text format. Always `text`
                         */
                        type: 'text';
                    } | {
                        type: 'grammar';
                        /**
                         * Your chosen grammar
                         */
                        grammar: {
                            /**
                             * The grammar definition
                             */
                            definition: string;
                            /**
                             * The syntax of the grammar definition
                             */
                            syntax: 'lark' | 'regex';
                        };
                    };
                };
            };
            temperature?: number | null;
            max_tokens?: number | null;
            stream?: boolean | null;
        };
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L248
         */
        response: {
            id: string;
            choices: Array<{
                finish_reason: 'stop' | 'length' | 'tool_calls' | 'content_filter' | 'function_call';
                index: number;
                logprobs: unknown;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1000
                 */
                message: {
                    content: string | null;
                    refusal: string | null;
                    role: 'assistant';
                    annotations?: Array<unknown>;
                    audio?: unknown;
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
                     */
                    function_call?: {
                        arguments: string;
                        name: string;
                    } | null;
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
                     */
                    tool_calls?: Array<{
                        id: string;
                        type: 'function';
                        /**
                         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                         */
                        function: {
                            arguments: string;
                            name: string;
                        };
                    } | {
                        id: string;
                        type: 'custom';
                        /**
                         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                         */
                        custom: {
                            input: string;
                            name: string;
                        };
                    }>;
                };
            }>;
            created: number;
            model: string;
            object: 'chat.completion';
            server_tier?: string;
            system_fingerprint?: string | null;
            /**
             * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L113
             */
            usage?: {
                completion_tokens: number;
                prompt_tokens: number;
                total_tokens: number;
                /**
                 * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L144
                 */
                completion_tokens_details?: unknown;
                /**
                 * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L173
                 */
                prompt_tokens_details?: unknown;
            };
        };
        createdAt: string;
    }>;
};

export type GetInteractionsResponse = GetInteractionsResponses[keyof GetInteractionsResponses];

export type GetInteractionData = {
    body?: never;
    path: {
        interactionId: string;
    };
    query?: never;
    url: '/api/interactions/{interactionId}';
};

export type GetInteractionErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetInteractionError = GetInteractionErrors[keyof GetInteractionErrors];

export type GetInteractionResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        agentId: string;
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1487
         */
        request: {
            model: string;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1186
             */
            messages: Array<{
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                role: 'developer';
                name?: string;
            } | {
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                role: 'system';
                name?: string;
            } | {
                content: string | Array<{
                    type: 'text';
                    text: string;
                } | {
                    type: 'image_url';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L765
                     */
                    image_url: {
                        url: string;
                        detail: 'auto' | 'low' | 'high';
                    };
                } | {
                    type: 'input_audio';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L792
                     */
                    input_audio: {
                        data: string;
                        format: 'wav' | 'mp3';
                    };
                } | {
                    type: 'file';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L732
                     */
                    file: {
                        file_data?: string;
                        file_id?: string;
                        filename?: string;
                    };
                }>;
                role: 'user';
                name?: string;
            } | {
                role: 'assistant';
                audio?: {
                    id: string;
                } | null;
                content?: string | Array<{
                    type: 'text';
                    text: string;
                }> | Array<{
                    type: 'refusal';
                    refusal: string;
                }> | null;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
                 */
                function_call?: {
                    arguments: string;
                    name: string;
                } | null;
                name?: string;
                refusal?: string | null;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
                 */
                tool_calls?: Array<{
                    id: string;
                    type: 'function';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                     */
                    function: {
                        arguments: string;
                        name: string;
                    };
                } | {
                    id: string;
                    type: 'custom';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                     */
                    custom: {
                        input: string;
                        name: string;
                    };
                }>;
            } | {
                role: 'tool';
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                tool_call_id: string;
            } | {
                role: 'function';
                content: string | null;
                name: string;
            }>;
            /**
             *
             * A function tool that can be used to generate a response.
             *
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1392
             *
             */
            tools?: Array<{
                type: 'function';
                /**
                 * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L174
                 */
                function: {
                    name: string;
                    description?: string;
                    /**
                     *
                     * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
                     *
                     * The parameters the functions accepts, described as a JSON Schema object. See the
                     * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
                     * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
                     * documentation about the format.
                     *
                     * Omitting parameters defines a function with an empty parameter list.
                     *
                     */
                    parameters?: {
                        [key: string]: unknown;
                    };
                    strict?: boolean | null;
                };
            } | {
                type: 'custom';
                custom: {
                    /**
                     * The name of the custom tool, used to identify it in tool calls
                     */
                    name: string;
                    /**
                     * Optional description of the custom tool, used to provide more context
                     */
                    description?: string;
                    /**
                     * The input format for the custom tool. Default is unconstrained text.
                     */
                    format?: {
                        /**
                         * Unconstrained text format. Always `text`
                         */
                        type: 'text';
                    } | {
                        type: 'grammar';
                        /**
                         * Your chosen grammar
                         */
                        grammar: {
                            /**
                             * The grammar definition
                             */
                            definition: string;
                            /**
                             * The syntax of the grammar definition
                             */
                            syntax: 'lark' | 'regex';
                        };
                    };
                };
            }>;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1405
             */
            tool_choice?: 'none' | 'auto' | 'required' | {
                type: 'allowed_tools';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1455
                 */
                allowed_tools: {
                    /**
                     *
                     * Constrains the tools available to the model to a pre-defined set.
                     *
                     * auto allows the model to pick from among the allowed tools and generate a
                     * message.
                     *
                     * required requires the model to call one or more of the allowed tools.
                     *
                     */
                    mode: 'auto' | 'required';
                    /**
                     * A list of tool definitions that the model should be allowed to call
                     */
                    tools: Array<{
                        [key: string]: {
                            type: 'function';
                            /**
                             * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L174
                             */
                            function: {
                                name: string;
                                description?: string;
                                /**
                                 *
                                 * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
                                 *
                                 * The parameters the functions accepts, described as a JSON Schema object. See the
                                 * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
                                 * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
                                 * documentation about the format.
                                 *
                                 * Omitting parameters defines a function with an empty parameter list.
                                 *
                                 */
                                parameters?: {
                                    [key: string]: unknown;
                                };
                                strict?: boolean | null;
                            };
                        };
                    }>;
                };
            } | {
                type: 'function';
                function: {
                    name: string;
                };
            } | {
                type: 'custom';
                custom: {
                    /**
                     * The name of the custom tool, used to identify it in tool calls
                     */
                    name: string;
                    /**
                     * Optional description of the custom tool, used to provide more context
                     */
                    description?: string;
                    /**
                     * The input format for the custom tool. Default is unconstrained text.
                     */
                    format?: {
                        /**
                         * Unconstrained text format. Always `text`
                         */
                        type: 'text';
                    } | {
                        type: 'grammar';
                        /**
                         * Your chosen grammar
                         */
                        grammar: {
                            /**
                             * The grammar definition
                             */
                            definition: string;
                            /**
                             * The syntax of the grammar definition
                             */
                            syntax: 'lark' | 'regex';
                        };
                    };
                };
            };
            temperature?: number | null;
            max_tokens?: number | null;
            stream?: boolean | null;
        };
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L248
         */
        response: {
            id: string;
            choices: Array<{
                finish_reason: 'stop' | 'length' | 'tool_calls' | 'content_filter' | 'function_call';
                index: number;
                logprobs: unknown;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1000
                 */
                message: {
                    content: string | null;
                    refusal: string | null;
                    role: 'assistant';
                    annotations?: Array<unknown>;
                    audio?: unknown;
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
                     */
                    function_call?: {
                        arguments: string;
                        name: string;
                    } | null;
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
                     */
                    tool_calls?: Array<{
                        id: string;
                        type: 'function';
                        /**
                         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                         */
                        function: {
                            arguments: string;
                            name: string;
                        };
                    } | {
                        id: string;
                        type: 'custom';
                        /**
                         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                         */
                        custom: {
                            input: string;
                            name: string;
                        };
                    }>;
                };
            }>;
            created: number;
            model: string;
            object: 'chat.completion';
            server_tier?: string;
            system_fingerprint?: string | null;
            /**
             * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L113
             */
            usage?: {
                completion_tokens: number;
                prompt_tokens: number;
                total_tokens: number;
                /**
                 * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L144
                 */
                completion_tokens_details?: unknown;
                /**
                 * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L173
                 */
                prompt_tokens_details?: unknown;
            };
        };
        createdAt: string;
    };
};

export type GetInteractionResponse = GetInteractionResponses[keyof GetInteractionResponses];

export type DeleteV1ByProviderData = {
    body?: never;
    path: {
        provider: string;
    };
    query?: never;
    url: '/v1/{provider}/';
};

export type DeleteV1ByProviderResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV1ByProviderData = {
    body?: never;
    path: {
        provider: string;
    };
    query?: never;
    url: '/v1/{provider}/';
};

export type GetV1ByProviderResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type HeadV1ByProviderData = {
    body?: never;
    path: {
        provider: string;
    };
    query?: never;
    url: '/v1/{provider}/';
};

export type HeadV1ByProviderResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type OptionsV1ByProviderData = {
    body?: never;
    path: {
        provider: string;
    };
    query?: never;
    url: '/v1/{provider}/';
};

export type OptionsV1ByProviderResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchV1ByProviderData = {
    body?: never;
    path: {
        provider: string;
    };
    query?: never;
    url: '/v1/{provider}/';
};

export type PatchV1ByProviderResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV1ByProviderData = {
    body?: never;
    path: {
        provider: string;
    };
    query?: never;
    url: '/v1/{provider}/';
};

export type PostV1ByProviderResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PutV1ByProviderData = {
    body?: never;
    path: {
        provider: string;
    };
    query?: never;
    url: '/v1/{provider}/';
};

export type PutV1ByProviderResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteV1ByProviderBy__Data = {
    body?: never;
    path: {
        provider: string;
        '*': string;
    };
    query?: never;
    url: '/v1/{provider}/{*}';
};

export type DeleteV1ByProviderBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV1ByProviderBy__Data = {
    body?: never;
    path: {
        provider: string;
        '*': string;
    };
    query?: never;
    url: '/v1/{provider}/{*}';
};

export type GetV1ByProviderBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type HeadV1ByProviderBy__Data = {
    body?: never;
    path: {
        provider: string;
        '*': string;
    };
    query?: never;
    url: '/v1/{provider}/{*}';
};

export type HeadV1ByProviderBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type OptionsV1ByProviderBy__Data = {
    body?: never;
    path: {
        provider: string;
        '*': string;
    };
    query?: never;
    url: '/v1/{provider}/{*}';
};

export type OptionsV1ByProviderBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchV1ByProviderBy__Data = {
    body?: never;
    path: {
        provider: string;
        '*': string;
    };
    query?: never;
    url: '/v1/{provider}/{*}';
};

export type PatchV1ByProviderBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV1ByProviderBy__Data = {
    body?: never;
    path: {
        provider: string;
        '*': string;
    };
    query?: never;
    url: '/v1/{provider}/{*}';
};

export type PostV1ByProviderBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PutV1ByProviderBy__Data = {
    body?: never;
    path: {
        provider: string;
        '*': string;
    };
    query?: never;
    url: '/v1/{provider}/{*}';
};

export type PutV1ByProviderBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type OpenAiChatCompletionsWithDefaultAgentData = {
    /**
     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1487
     */
    body: {
        model: string;
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1186
         */
        messages: Array<{
            content: string | Array<{
                type: 'text';
                text: string;
            }>;
            role: 'developer';
            name?: string;
        } | {
            content: string | Array<{
                type: 'text';
                text: string;
            }>;
            role: 'system';
            name?: string;
        } | {
            content: string | Array<{
                type: 'text';
                text: string;
            } | {
                type: 'image_url';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L765
                 */
                image_url: {
                    url: string;
                    detail: 'auto' | 'low' | 'high';
                };
            } | {
                type: 'input_audio';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L792
                 */
                input_audio: {
                    data: string;
                    format: 'wav' | 'mp3';
                };
            } | {
                type: 'file';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L732
                 */
                file: {
                    file_data?: string;
                    file_id?: string;
                    filename?: string;
                };
            }>;
            role: 'user';
            name?: string;
        } | {
            role: 'assistant';
            audio?: {
                id: string;
            } | null;
            content?: string | Array<{
                type: 'text';
                text: string;
            }> | Array<{
                type: 'refusal';
                refusal: string;
            }> | null;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
             */
            function_call?: {
                arguments: string;
                name: string;
            } | null;
            name?: string;
            refusal?: string | null;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
             */
            tool_calls?: Array<{
                id: string;
                type: 'function';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                 */
                function: {
                    arguments: string;
                    name: string;
                };
            } | {
                id: string;
                type: 'custom';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                 */
                custom: {
                    input: string;
                    name: string;
                };
            }>;
        } | {
            role: 'tool';
            content: string | Array<{
                type: 'text';
                text: string;
            }>;
            tool_call_id: string;
        } | {
            role: 'function';
            content: string | null;
            name: string;
        }>;
        /**
         *
         * A function tool that can be used to generate a response.
         *
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1392
         *
         */
        tools?: Array<{
            type: 'function';
            /**
             * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L174
             */
            function: {
                name: string;
                description?: string;
                /**
                 *
                 * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
                 *
                 * The parameters the functions accepts, described as a JSON Schema object. See the
                 * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
                 * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
                 * documentation about the format.
                 *
                 * Omitting parameters defines a function with an empty parameter list.
                 *
                 */
                parameters?: {
                    [key: string]: unknown;
                };
                strict?: boolean | null;
            };
        } | {
            type: 'custom';
            custom: {
                /**
                 * The name of the custom tool, used to identify it in tool calls
                 */
                name: string;
                /**
                 * Optional description of the custom tool, used to provide more context
                 */
                description?: string;
                /**
                 * The input format for the custom tool. Default is unconstrained text.
                 */
                format?: {
                    /**
                     * Unconstrained text format. Always `text`
                     */
                    type: 'text';
                } | {
                    type: 'grammar';
                    /**
                     * Your chosen grammar
                     */
                    grammar: {
                        /**
                         * The grammar definition
                         */
                        definition: string;
                        /**
                         * The syntax of the grammar definition
                         */
                        syntax: 'lark' | 'regex';
                    };
                };
            };
        }>;
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1405
         */
        tool_choice?: 'none' | 'auto' | 'required' | {
            type: 'allowed_tools';
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1455
             */
            allowed_tools: {
                /**
                 *
                 * Constrains the tools available to the model to a pre-defined set.
                 *
                 * auto allows the model to pick from among the allowed tools and generate a
                 * message.
                 *
                 * required requires the model to call one or more of the allowed tools.
                 *
                 */
                mode: 'auto' | 'required';
                /**
                 * A list of tool definitions that the model should be allowed to call
                 */
                tools: Array<{
                    [key: string]: {
                        type: 'function';
                        /**
                         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L174
                         */
                        function: {
                            name: string;
                            description?: string;
                            /**
                             *
                             * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
                             *
                             * The parameters the functions accepts, described as a JSON Schema object. See the
                             * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
                             * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
                             * documentation about the format.
                             *
                             * Omitting parameters defines a function with an empty parameter list.
                             *
                             */
                            parameters?: {
                                [key: string]: unknown;
                            };
                            strict?: boolean | null;
                        };
                    };
                }>;
            };
        } | {
            type: 'function';
            function: {
                name: string;
            };
        } | {
            type: 'custom';
            custom: {
                /**
                 * The name of the custom tool, used to identify it in tool calls
                 */
                name: string;
                /**
                 * Optional description of the custom tool, used to provide more context
                 */
                description?: string;
                /**
                 * The input format for the custom tool. Default is unconstrained text.
                 */
                format?: {
                    /**
                     * Unconstrained text format. Always `text`
                     */
                    type: 'text';
                } | {
                    type: 'grammar';
                    /**
                     * Your chosen grammar
                     */
                    grammar: {
                        /**
                         * The grammar definition
                         */
                        definition: string;
                        /**
                         * The syntax of the grammar definition
                         */
                        syntax: 'lark' | 'regex';
                    };
                };
            };
        };
        temperature?: number | null;
        max_tokens?: number | null;
        stream?: boolean | null;
    };
    headers: {
        /**
         * If specified, interactions will be associated with this chat, otherwise a new chat will be created
         */
        'x-archestra-chat-id'?: string;
        /**
         * The user agent of the client
         */
        'user-agent'?: string;
        /**
         * Bearer token for OpenAI
         */
        authorization: string;
    };
    path?: never;
    query?: never;
    url: '/v1/openai/chat/completions';
};

export type OpenAiChatCompletionsWithDefaultAgentErrors = {
    /**
     * Default Response
     */
    400: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    403: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type OpenAiChatCompletionsWithDefaultAgentError = OpenAiChatCompletionsWithDefaultAgentErrors[keyof OpenAiChatCompletionsWithDefaultAgentErrors];

export type OpenAiChatCompletionsWithDefaultAgentResponses = {
    /**
     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L248
     */
    200: {
        id: string;
        choices: Array<{
            finish_reason: 'stop' | 'length' | 'tool_calls' | 'content_filter' | 'function_call';
            index: number;
            logprobs: unknown;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1000
             */
            message: {
                content: string | null;
                refusal: string | null;
                role: 'assistant';
                annotations?: Array<unknown>;
                audio?: unknown;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
                 */
                function_call?: {
                    arguments: string;
                    name: string;
                } | null;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
                 */
                tool_calls?: Array<{
                    id: string;
                    type: 'function';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                     */
                    function: {
                        arguments: string;
                        name: string;
                    };
                } | {
                    id: string;
                    type: 'custom';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                     */
                    custom: {
                        input: string;
                        name: string;
                    };
                }>;
            };
        }>;
        created: number;
        model: string;
        object: 'chat.completion';
        server_tier?: string;
        system_fingerprint?: string | null;
        /**
         * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L113
         */
        usage?: {
            completion_tokens: number;
            prompt_tokens: number;
            total_tokens: number;
            /**
             * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L144
             */
            completion_tokens_details?: unknown;
            /**
             * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L173
             */
            prompt_tokens_details?: unknown;
        };
    };
};

export type OpenAiChatCompletionsWithDefaultAgentResponse = OpenAiChatCompletionsWithDefaultAgentResponses[keyof OpenAiChatCompletionsWithDefaultAgentResponses];

export type OpenAiChatCompletionsWithAgentData = {
    /**
     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1487
     */
    body: {
        model: string;
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1186
         */
        messages: Array<{
            content: string | Array<{
                type: 'text';
                text: string;
            }>;
            role: 'developer';
            name?: string;
        } | {
            content: string | Array<{
                type: 'text';
                text: string;
            }>;
            role: 'system';
            name?: string;
        } | {
            content: string | Array<{
                type: 'text';
                text: string;
            } | {
                type: 'image_url';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L765
                 */
                image_url: {
                    url: string;
                    detail: 'auto' | 'low' | 'high';
                };
            } | {
                type: 'input_audio';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L792
                 */
                input_audio: {
                    data: string;
                    format: 'wav' | 'mp3';
                };
            } | {
                type: 'file';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L732
                 */
                file: {
                    file_data?: string;
                    file_id?: string;
                    filename?: string;
                };
            }>;
            role: 'user';
            name?: string;
        } | {
            role: 'assistant';
            audio?: {
                id: string;
            } | null;
            content?: string | Array<{
                type: 'text';
                text: string;
            }> | Array<{
                type: 'refusal';
                refusal: string;
            }> | null;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
             */
            function_call?: {
                arguments: string;
                name: string;
            } | null;
            name?: string;
            refusal?: string | null;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
             */
            tool_calls?: Array<{
                id: string;
                type: 'function';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                 */
                function: {
                    arguments: string;
                    name: string;
                };
            } | {
                id: string;
                type: 'custom';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                 */
                custom: {
                    input: string;
                    name: string;
                };
            }>;
        } | {
            role: 'tool';
            content: string | Array<{
                type: 'text';
                text: string;
            }>;
            tool_call_id: string;
        } | {
            role: 'function';
            content: string | null;
            name: string;
        }>;
        /**
         *
         * A function tool that can be used to generate a response.
         *
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1392
         *
         */
        tools?: Array<{
            type: 'function';
            /**
             * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L174
             */
            function: {
                name: string;
                description?: string;
                /**
                 *
                 * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
                 *
                 * The parameters the functions accepts, described as a JSON Schema object. See the
                 * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
                 * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
                 * documentation about the format.
                 *
                 * Omitting parameters defines a function with an empty parameter list.
                 *
                 */
                parameters?: {
                    [key: string]: unknown;
                };
                strict?: boolean | null;
            };
        } | {
            type: 'custom';
            custom: {
                /**
                 * The name of the custom tool, used to identify it in tool calls
                 */
                name: string;
                /**
                 * Optional description of the custom tool, used to provide more context
                 */
                description?: string;
                /**
                 * The input format for the custom tool. Default is unconstrained text.
                 */
                format?: {
                    /**
                     * Unconstrained text format. Always `text`
                     */
                    type: 'text';
                } | {
                    type: 'grammar';
                    /**
                     * Your chosen grammar
                     */
                    grammar: {
                        /**
                         * The grammar definition
                         */
                        definition: string;
                        /**
                         * The syntax of the grammar definition
                         */
                        syntax: 'lark' | 'regex';
                    };
                };
            };
        }>;
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1405
         */
        tool_choice?: 'none' | 'auto' | 'required' | {
            type: 'allowed_tools';
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1455
             */
            allowed_tools: {
                /**
                 *
                 * Constrains the tools available to the model to a pre-defined set.
                 *
                 * auto allows the model to pick from among the allowed tools and generate a
                 * message.
                 *
                 * required requires the model to call one or more of the allowed tools.
                 *
                 */
                mode: 'auto' | 'required';
                /**
                 * A list of tool definitions that the model should be allowed to call
                 */
                tools: Array<{
                    [key: string]: {
                        type: 'function';
                        /**
                         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L174
                         */
                        function: {
                            name: string;
                            description?: string;
                            /**
                             *
                             * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
                             *
                             * The parameters the functions accepts, described as a JSON Schema object. See the
                             * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
                             * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
                             * documentation about the format.
                             *
                             * Omitting parameters defines a function with an empty parameter list.
                             *
                             */
                            parameters?: {
                                [key: string]: unknown;
                            };
                            strict?: boolean | null;
                        };
                    };
                }>;
            };
        } | {
            type: 'function';
            function: {
                name: string;
            };
        } | {
            type: 'custom';
            custom: {
                /**
                 * The name of the custom tool, used to identify it in tool calls
                 */
                name: string;
                /**
                 * Optional description of the custom tool, used to provide more context
                 */
                description?: string;
                /**
                 * The input format for the custom tool. Default is unconstrained text.
                 */
                format?: {
                    /**
                     * Unconstrained text format. Always `text`
                     */
                    type: 'text';
                } | {
                    type: 'grammar';
                    /**
                     * Your chosen grammar
                     */
                    grammar: {
                        /**
                         * The grammar definition
                         */
                        definition: string;
                        /**
                         * The syntax of the grammar definition
                         */
                        syntax: 'lark' | 'regex';
                    };
                };
            };
        };
        temperature?: number | null;
        max_tokens?: number | null;
        stream?: boolean | null;
    };
    headers: {
        /**
         * If specified, interactions will be associated with this chat, otherwise a new chat will be created
         */
        'x-archestra-chat-id'?: string;
        /**
         * The user agent of the client
         */
        'user-agent'?: string;
        /**
         * Bearer token for OpenAI
         */
        authorization: string;
    };
    path: {
        agentId: string;
    };
    query?: never;
    url: '/v1/openai/{agentId}/chat/completions';
};

export type OpenAiChatCompletionsWithAgentErrors = {
    /**
     * Default Response
     */
    400: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    403: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type OpenAiChatCompletionsWithAgentError = OpenAiChatCompletionsWithAgentErrors[keyof OpenAiChatCompletionsWithAgentErrors];

export type OpenAiChatCompletionsWithAgentResponses = {
    /**
     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L248
     */
    200: {
        id: string;
        choices: Array<{
            finish_reason: 'stop' | 'length' | 'tool_calls' | 'content_filter' | 'function_call';
            index: number;
            logprobs: unknown;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1000
             */
            message: {
                content: string | null;
                refusal: string | null;
                role: 'assistant';
                annotations?: Array<unknown>;
                audio?: unknown;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
                 */
                function_call?: {
                    arguments: string;
                    name: string;
                } | null;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
                 */
                tool_calls?: Array<{
                    id: string;
                    type: 'function';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                     */
                    function: {
                        arguments: string;
                        name: string;
                    };
                } | {
                    id: string;
                    type: 'custom';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                     */
                    custom: {
                        input: string;
                        name: string;
                    };
                }>;
            };
        }>;
        created: number;
        model: string;
        object: 'chat.completion';
        server_tier?: string;
        system_fingerprint?: string | null;
        /**
         * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L113
         */
        usage?: {
            completion_tokens: number;
            prompt_tokens: number;
            total_tokens: number;
            /**
             * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L144
             */
            completion_tokens_details?: unknown;
            /**
             * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L173
             */
            prompt_tokens_details?: unknown;
        };
    };
};

export type OpenAiChatCompletionsWithAgentResponse = OpenAiChatCompletionsWithAgentResponses[keyof OpenAiChatCompletionsWithAgentResponses];

export type GetToolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tools';
};

export type GetToolsErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetToolsError = GetToolsErrors[keyof GetToolsErrors];

export type GetToolsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        /**
         *
         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
         *
         * The parameters the functions accepts, described as a JSON Schema object. See the
         * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
         * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
         * documentation about the format.
         *
         * Omitting parameters defines a function with an empty parameter list.
         *
         */
        parameters?: {
            [key: string]: unknown;
        };
        description: string | null;
        allowUsageWhenUntrustedDataIsPresent: boolean;
        dataIsTrustedByDefault: boolean;
        createdAt: string;
        updatedAt: string;
        agent: {
            id: string;
            name: string;
        };
    }>;
};

export type GetToolsResponse = GetToolsResponses[keyof GetToolsResponses];

export type UpdateToolData = {
    body?: {
        id?: string;
        agentId?: string;
        name?: string;
        /**
         *
         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
         *
         * The parameters the functions accepts, described as a JSON Schema object. See the
         * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
         * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
         * documentation about the format.
         *
         * Omitting parameters defines a function with an empty parameter list.
         *
         */
        parameters?: {
            [key: string]: unknown;
        };
        description?: string | null;
        allowUsageWhenUntrustedDataIsPresent?: boolean;
        dataIsTrustedByDefault?: boolean;
        createdAt?: unknown;
        updatedAt?: unknown;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tools/{id}';
};

export type UpdateToolErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UpdateToolError = UpdateToolErrors[keyof UpdateToolErrors];

export type UpdateToolResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        agentId: string;
        name: string;
        /**
         *
         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
         *
         * The parameters the functions accepts, described as a JSON Schema object. See the
         * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
         * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
         * documentation about the format.
         *
         * Omitting parameters defines a function with an empty parameter list.
         *
         */
        parameters?: {
            [key: string]: unknown;
        };
        description: string | null;
        allowUsageWhenUntrustedDataIsPresent: boolean;
        dataIsTrustedByDefault: boolean;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateToolResponse = UpdateToolResponses[keyof UpdateToolResponses];

export type GetOperatorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/autonomy-policies/operators';
};

export type GetOperatorsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        value: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        label: string;
    }>;
};

export type GetOperatorsResponse = GetOperatorsResponses[keyof GetOperatorsResponses];

export type GetToolInvocationPoliciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/autonomy-policies/tool-invocation';
};

export type GetToolInvocationPoliciesErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetToolInvocationPoliciesError = GetToolInvocationPoliciesErrors[keyof GetToolInvocationPoliciesErrors];

export type GetToolInvocationPoliciesResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        toolId: string;
        argumentName: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'allow_when_context_is_untrusted' | 'block_always';
        reason: string | null;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetToolInvocationPoliciesResponse = GetToolInvocationPoliciesResponses[keyof GetToolInvocationPoliciesResponses];

export type CreateToolInvocationPolicyData = {
    body: {
        toolId: string;
        argumentName: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'allow_when_context_is_untrusted' | 'block_always';
        reason?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/autonomy-policies/tool-invocation';
};

export type CreateToolInvocationPolicyErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type CreateToolInvocationPolicyError = CreateToolInvocationPolicyErrors[keyof CreateToolInvocationPolicyErrors];

export type CreateToolInvocationPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        argumentName: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'allow_when_context_is_untrusted' | 'block_always';
        reason: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateToolInvocationPolicyResponse = CreateToolInvocationPolicyResponses[keyof CreateToolInvocationPolicyResponses];

export type DeleteToolInvocationPolicyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/autonomy-policies/tool-invocation/{id}';
};

export type DeleteToolInvocationPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type DeleteToolInvocationPolicyError = DeleteToolInvocationPolicyErrors[keyof DeleteToolInvocationPolicyErrors];

export type DeleteToolInvocationPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
    };
};

export type DeleteToolInvocationPolicyResponse = DeleteToolInvocationPolicyResponses[keyof DeleteToolInvocationPolicyResponses];

export type GetToolInvocationPolicyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/autonomy-policies/tool-invocation/{id}';
};

export type GetToolInvocationPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetToolInvocationPolicyError = GetToolInvocationPolicyErrors[keyof GetToolInvocationPolicyErrors];

export type GetToolInvocationPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        argumentName: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'allow_when_context_is_untrusted' | 'block_always';
        reason: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetToolInvocationPolicyResponse = GetToolInvocationPolicyResponses[keyof GetToolInvocationPolicyResponses];

export type UpdateToolInvocationPolicyData = {
    body?: {
        toolId?: string;
        argumentName?: string;
        operator?: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value?: string;
        action?: 'allow_when_context_is_untrusted' | 'block_always';
        reason?: string | null;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/autonomy-policies/tool-invocation/{id}';
};

export type UpdateToolInvocationPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UpdateToolInvocationPolicyError = UpdateToolInvocationPolicyErrors[keyof UpdateToolInvocationPolicyErrors];

export type UpdateToolInvocationPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        argumentName: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'allow_when_context_is_untrusted' | 'block_always';
        reason: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateToolInvocationPolicyResponse = UpdateToolInvocationPolicyResponses[keyof UpdateToolInvocationPolicyResponses];

export type GetTrustedDataPoliciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/trusted-data-policies';
};

export type GetTrustedDataPoliciesErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetTrustedDataPoliciesError = GetTrustedDataPoliciesErrors[keyof GetTrustedDataPoliciesErrors];

export type GetTrustedDataPoliciesResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        toolId: string;
        description: string;
        attributePath: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'block_always' | 'mark_as_trusted';
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetTrustedDataPoliciesResponse = GetTrustedDataPoliciesResponses[keyof GetTrustedDataPoliciesResponses];

export type CreateTrustedDataPolicyData = {
    body: {
        toolId: string;
        description: string;
        attributePath: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'block_always' | 'mark_as_trusted';
    };
    path?: never;
    query?: never;
    url: '/api/trusted-data-policies';
};

export type CreateTrustedDataPolicyErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type CreateTrustedDataPolicyError = CreateTrustedDataPolicyErrors[keyof CreateTrustedDataPolicyErrors];

export type CreateTrustedDataPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        description: string;
        attributePath: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'block_always' | 'mark_as_trusted';
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateTrustedDataPolicyResponse = CreateTrustedDataPolicyResponses[keyof CreateTrustedDataPolicyResponses];

export type DeleteTrustedDataPolicyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/trusted-data-policies/{id}';
};

export type DeleteTrustedDataPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type DeleteTrustedDataPolicyError = DeleteTrustedDataPolicyErrors[keyof DeleteTrustedDataPolicyErrors];

export type DeleteTrustedDataPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
    };
};

export type DeleteTrustedDataPolicyResponse = DeleteTrustedDataPolicyResponses[keyof DeleteTrustedDataPolicyResponses];

export type GetTrustedDataPolicyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/trusted-data-policies/{id}';
};

export type GetTrustedDataPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetTrustedDataPolicyError = GetTrustedDataPolicyErrors[keyof GetTrustedDataPolicyErrors];

export type GetTrustedDataPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        description: string;
        attributePath: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'block_always' | 'mark_as_trusted';
        createdAt: string;
        updatedAt: string;
    };
};

export type GetTrustedDataPolicyResponse = GetTrustedDataPolicyResponses[keyof GetTrustedDataPolicyResponses];

export type UpdateTrustedDataPolicyData = {
    body?: {
        toolId?: string;
        description?: string;
        attributePath?: string;
        operator?: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value?: string;
        action?: 'block_always' | 'mark_as_trusted';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/trusted-data-policies/{id}';
};

export type UpdateTrustedDataPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UpdateTrustedDataPolicyError = UpdateTrustedDataPolicyErrors[keyof UpdateTrustedDataPolicyErrors];

export type UpdateTrustedDataPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        description: string;
        attributePath: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'block_always' | 'mark_as_trusted';
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateTrustedDataPolicyResponse = UpdateTrustedDataPolicyResponses[keyof UpdateTrustedDataPolicyResponses];
