# NOTE! This workflow will only run if the pull request was opened by
# the below configured users.
#
# It will "invoke Claude" using the user's specific OAuth token. This is being done so that
# we respect Anthropic's terms-of-service wrt Max accounts/oauth tokens only being able to be
# used by a single account.
#
# See here for more details:
# https://github.com/anthropics/claude-code-action/issues/4#issuecomment-3046770474
name: Claude Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches-ignore:
      - release-please--branches--main

concurrency:
  # Cancel any running workflow for the same branch when new commits are pushed.
  # We group both by ref_name (available when CI is triggered by a push to a branch/tag)
  # and head_ref (available when CI is triggered by a PR).
  group: "claude-pull-requests-${{ github.ref_name }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  joey-claude-pull-requests:
    name: Claude Pull Requests for Joey
    if: |
      github.event.pull_request.user.login == 'joeyorlando'
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    uses: ./.github/workflows/claude-pull-requests.yml
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.JOEYORLANDO_CLAUDE_CODE_OAUTH_TOKEN }}

  ildar-claude-pull-requests:
    name: Claude Pull Requests for Ildar
    if: |
      github.event.pull_request.user.login == 'iskhakov'
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    uses: ./.github/workflows/claude-pull-requests.yml
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.ILDAR_CLAUDE_CODE_OAUTH_TOKEN }}
